apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-{{ .Values.color }}   # unique deployment name per color
  labels:
    app: {{ .Values.color }}-webserver
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webserver
      ver: {{ .Values.color }}       # match pods by color
  template:
    metadata:
      labels:
        app: webserver
        ver: {{ .Values.color }}     # pods get color label
    spec:
      containers:
        - name: webserver-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
